modoboa_amavis/urls.py
# -*- coding: utf-8 -*-

"""Amavis urls."""

from django.urls import path

from . import views

app_name = 'modoboa_amavis'

urlpatterns = [
    path('', views.index, name="index"),
    path('listing/', views._listing, name="_mail_list"),
    path('listing/page/', views.listing_page, name="mail_page"),
    path('getmailcontent/<str:mail_id>/', views.getmailcontent,
         name="mailcontent_get"),
    path('process/', views.process, name="mail_process"),
    path('delete/<str:mail_id>/', views.delete, name="mail_delete"),
    path('release/<str:mail_id>/', views.release,
         name="mail_release"),
    path('markspam/<str:mail_id>/', views.mark_as_spam,
         name="mail_mark_as_spam"),
    path('markham/<str:mail_id>/', views.mark_as_ham,
         name="mail_mark_as_ham"),
    path('learning_recipient/', views.learning_recipient,
         name="learning_recipient_set"),
    path('<str:mail_id>/', views.viewmail, name="mail_detail"),
    path('<str:mail_id>/headers/', views.viewheaders,
         name="headers_detail"),
]

modoboa_amavis/templates/modoboa_amavis/_email_display.html
<iframe src="{% url 'modoboa_amavis:mailcontent_get' mail_id %}" id="mailcontent"></iframe>

modoboa_amavis/templates/modoboa_amavis/domain_content_filter.html
{% load i18n form_tags %}
{% render_field form.bypass_virus_checks %}
{% render_field form.bypass_spam_checks %}
<div class="form-group">
  <label class="control-label col-lg-4 col-md-4 col-sm-4">{% trans "Thresholds" %}</label>
  <div class="col-lg-2 col-md-2 col-sm-2">
    {{ form.spam_tag2_level }}
  </div>
  <span class="help-block">{% trans "or more is spam" %}</span>
</div>
<div class="form-group">
  <div class="col-sm-offset-4 col-lg-2 col-md-2 col-sm-2">
    {{ form.spam_kill_level }}
  </div>
  <span class="help-block">{% trans "or more throw spam message away" %}</span>
</div>
{% render_field form.spam_subject_tag2 activator=True activator_label=_("default") activator_size="col-sm-3" %}
{% render_field form.bypass_banned_checks %}

modoboa_amavis/templates/modoboa_amavis/email_list.html
{% extends "modoboa_amavis/quarantine.html" %}

{% load i18n %}

{% block main %}
  <form method="POST" id="listingform">
    <table id="emails" class="table table-condensed">
      <thead>
        <tr>
          <th id="selection" width="5px"></th>
          <th id="type" width="30px" class="sortable sort-header" align="center" data-sort_order="type"></th>
          <th id="rstatus" width="25px"></th>
          <th id="score" class="sortable sort-header" data-sort_order="score">
            {% trans "Score" %}
          </th>
          <th id="to" class="sortable sort-header" data-sort_order="to">
            {% trans "To" %}
          </th>
          <th id="from" class="sortable sort-header" data-sort_order="from">
            {% trans "From" %}
          </th>
          <th id="subject" class="sortable sort-header" data-sort_order="subject">
            {% trans "Subject" %}
          </th>
          <th id="date" class="sortable sort-header" data-sort_order="date">
            {% trans "Date" %}
          </th>
        </tr>
      </thead>
      <tbody>
        {% include "modoboa_amavis/emails_page.html" %}
      </tbody>
    </table>
  </form>
{% endblock %}

modoboa_amavis/templates/modoboa_amavis/emails_page.html
{% load i18n %}
{% load amavis_tags %}
{% load static %}

{% for email in email_list %}
<tr id="{{ email.mailid }}">
  <td name="selection" width="5px">
    <input id="selection" type="checkbox" name="select_{{ email.mailid }}" value="{{ email.mailid }}">
  </td>
  <td align="center" width="30px" name="type" class="{{ email.class }}">
    {{ email.type|msgtype_to_html }}
  </td>
  <td width="25px" name="rstatus">
    {% if email.status == 'R' %}
    <span class="fa fa-mail-reply" title="{% trans 'Released' %}"></span>
    {% elif email.status == 'S' %}
    <span class="fa fa-thumbs-down" title="{% trans 'Marked as spam' %}"></span>
    {% elif email.status == 'H' %}
    <span class="fa fa-thumbs-up" title="{% trans 'Marked as non-spam' %}"></span>
    {% endif %}
  </td>
  <td class="openable {{ email.class }}" name="score">{{ email.score }}</td>
  <td class="openable {{ email.class }}" name="to">{{ email.to }}</td>
  <td class="openable {{ email.class }}" name="from" title="{{ email.from }}">
    {{ email.from|truncatechars:30 }}
  </td>
  <td class="openable {{ email.class }}" name="subject" title="{{ email.subject }}">
    {{ email.subject|truncatechars:30 }}
  </td>
  <td class="openable {{ email.class }}" name="date">
    {{ email.date|date:"SHORT_DATETIME_FORMAT" }}
  </td>
</tr>
{% endfor %}

modoboa_amavis/templates/modoboa_amavis/empty_quarantine.html
{% extends "modoboa_amavis/quarantine.html" %}

{% load i18n %}

{% block main %}
  <div class="alert alert-info">{% trans "Empty quarantine" %}</div>
{% endblock %}

modoboa_amavis/templates/modoboa_amavis/getmailcontent.html
{% if pre %}<pre>{% endif %}{{ body }}{% if pre %}</pre>{% endif %}

modoboa_amavis/templates/modoboa_amavis/index.html
{% extends "fluid.html" %}{% load i18n amavis_tags %}
{% load static %}

{% block pagetitle %}{% trans "Quarantine management" %}{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'modoboa_amavis/css/quarantine.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.sortable.css' %}" />
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/jquery.htmltable.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.infinitescroll.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.sortable.js' %}"></script>
<script type="text/javascript" src="{% static 'js/history.js' %}"></script>
<script type="text/javascript" src="{% static 'js/searchbar.js' %}"></script>
<script type="text/javascript" src="{% static 'js/listing.js' %}"></script>
<script type="text/javascript" src="{% static 'modoboa_amavis/js/quarantine.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    var qm = new Quarantine({
        deflocation: "listing/?sort_order=-date&reset_page=true",
        defcallback: "listing_cb",
        load_page_url: "{% url 'modoboa_amavis:mail_page' %}",
        check_learning_rcpt: {{ check_learning_rcpt }},
        learning_recipient_url: "{% url 'modoboa_amavis:learning_recipient_set' %}"
    });
});
</script>
{% endblock %}

{% block container_content %}
<div id="menubar">
  {% quar_menu user %}
</div>
<div id="listing"></div>
{% endblock %}

modoboa_amavis/templates/modoboa_amavis/mailheaders.html
{% extends "common/mailheaders.html" %}

{% block emailheaders %}

{% if qtype %}<div class="alert alert-danger"><strong>{{ qtype }}</strong> {{ qreason }}</div>{% endif %}
{{ block.super }}

{% endblock %}

modoboa_amavis/templates/modoboa_amavis/main_action_bar.html
{% load lib_tags i18n %}
<div class="row">

  <div class="col-xs-7 col-md-5 col-lg-4">
    <div class="btn-group" title="{% trans 'Select' %}">
      <a class="btn btn-default"><input type="checkbox" id="selectall" /></a>
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        {% for type, label in msg_types.items %}
        <li><a name="selectmsgs" href="{{ type }}"">{{ label }}</a></li>
        {% endfor %}
      </ul>
    </div>
    
    <div class="btn-group" title="{% trans 'Release' %}">
      <a name="release-multi" href="{% url 'modoboa_amavis:mail_process' %}" class="btn btn-success disabled">
        <span class="fa fa-check"></span> {% trans 'Release' %}
      </a>
    </div>
    <div class="btn-group" title="{% trans 'Delete' %}">
      <a name="delete-multi" href="{% url 'modoboa_amavis:mail_process' %}" class="btn btn-danger disabled">
        <span class="fa fa-trash"></span> {% trans 'Delete' %}
      </a>
    </div>
    {% if manual_learning %}
    <div class="btn-group" title="{% trans 'Manual learning' %}">
      <button class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="fa fa-cog"></span> <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a name="mark-as-spam-multi" href="{% url 'modoboa_amavis:mail_process' %}">{% trans "Mark as spam" %}</a></li>
        <li><a name="mark-as-ham-multi" href="{% url 'modoboa_amavis:mail_process' %}">{% trans "Mark as non-spam" %}</a></li>
      </ul>
    </div>
    {% endif %}

  </div>
  
  <div class="col-xs-5 col-lg-4">
    {% include "common/email_searchbar.html" with extraopts=extraopts %}
  </div>
  
</div>

modoboa_amavis/templates/modoboa_amavis/quarantine.html
{% load amavis_tags i18n %}

<div class="row" style="padding-top: 10px">
  <div class="col-sm-11">
    {% block main %}{% endblock %}
  </div>

  <div id="right_menu_bar" class="col-sm-1 text-center">
    {% block right_menu_bar %}
      <p><strong>{% trans "Display" %}</strong></p>
      <div id="filters" class="btn-group-vertical" data-toggle="buttons">
        <label class="btn btn-default active">
          <input type="radio" name="msgtype_all" title="{% trans 'All messages' %}" checked> {% trans "All" %}
        </label>
        {% for type, label in message_types.items %}
          <label class="btn btn-{{ type|msgtype_to_color }}" title="{{ label }}">
            <input type="radio" name="msgtype_{{ type }}" title="{{ label }}"> {{ type }}
          </label>
        {% endfor %}
      </div>
    {% endblock %}
  </div>
</div>

modoboa_amavis/templates/modoboa_amavis/viewheader.html
<pre id="rawheaders" class="well">
{% for k, v in headers %}{{ k }}: {{ v }}
{% endfor %}
</pre>

modoboa_amavis/templates/modoboa_amavis/viewmail_selfservice.html
<!DOCTYPE html>{% load i18n lib_tags amavis_tags %}
{% load static %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Modoboa</title>
    <link rel="icon" type="image/png" href="{% static 'css/logo-icon.png' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'modoboa_amavis/css/selfservice.css' %}" />
  </head>
  
  <body>
    <div id="fixed_content">
      <div id="menubar">{% viewm_menu_simple user mail_id rcpt secret_id %}</div>
      <div id="listing">{% include "modoboa_amavis/_email_display.html" %}</div>
    </div>

    <script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/global.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/notify.js' %}" type="text/javascript"></script>
    <script src="{% static 'modoboa_amavis/js/selfservice.js' %}" type="text/javascript"></script>
    {% url "django.views.i18n.javascript_catalog" as catalog_url %}
    <script type="text/javascript" src="{{ catalog_url }}"></script>
    <script type="text/javascript">
        set_media_url("{{ STATIC_URL }}");
    </script>
  </body>
</html>